# Generated by Django 4.2.7 on 2025-03-08 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='auther',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='music',
            old_name='auther',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='story',
            old_name='auther',
            new_name='user',
        ),
    ]
