# Generated by Django 5.2.6 on 2025-10-16 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['username'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.PositiveSmallIntegerField(default=1, error_messages={'unique': 'This phone number already exists.'}, help_text='Required. 15 characters or fewer.', max_length=15, unique=True),
            preserve_default=False,
        ),
    ]
