# Generated by Django 5.2.6 on 2025-10-16 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_options_customuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(error_messages={'unique': 'This phone number already exists.'}, help_text='Required. 15 characters or fewer.', max_length=15, unique=True),
        ),
    ]
