# Generated by Django 5.2.3 on 2025-06-22 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_customuser_age_remove_customuser_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, default='accounts/images/default-pic.png', null=True, upload_to='accounts/images/'),
        ),
    ]
