# Generated by Django 5.2.3 on 2025-12-15 17:39

import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='website_url',
            field=models.URLField(blank=True, help_text='100 characters or fewer. must starts with https://', max_length=100, null=True, validators=[utils.validators.URLValidator()]),
        ),
    ]
