# Generated by Django 4.2.7 on 2025-03-08 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_postsave_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='auther',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='auther',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='auther',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='postsave',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saves', to='base.post'),
        ),
    ]
